use_frameworks!

target 'VCHTTPConnect_Example' do
  pod 'VCHTTPConnect', :path => '../'
  pod 'Alamofire', '4.4'
  pod 'ObjectMapper', '2.2'
  pod 'VCSwiftToolkit', :git => 'https://github.com/ripventura/VCSwiftToolkit.git'
  
  target 'VCHTTPConnect_Tests' do
    inherit! :search_paths

    
  end
end
